- name: Pull backend Docker image
  community.docker.docker_image:
    name: "{{ backend_image }}"
    source: pull

- name: Start backend container
  community.docker.docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image }}"
    state: started
    restart_policy: always
    network_mode: "{{ docker_network_name }}"
    ports:
      - "{{ backend_port }}:5000"
    env:
      NODE_ENV: "{{ node_env }}"
      MONGO_URI: "mongodb://{{ mongodb_container_name }}:{{ mongodb_port }}/{{ mongodb_database }}"
      PORT: "{{ backend_port | quote }}"  

- name: Wait for backend to be ready
  uri:
    url: "http://localhost:{{ backend_port }}/api/health"
    status_code: 200
  register: result
  until: result.status == 200
  retries: 60
  delay: 1
