---
- block:
    - name: Pull backend Docker image
      community.docker.docker_image:
        name: "{{ backend_image }}"
        source: pull
  rescue:
    - name: Build backend Docker image locally if pull fails
      community.docker.docker_image:
        name: "{{ backend_image }}"
        build:
          path: "{{ backend_build_dir | default('./backend') }}"
      register: backend_build_result

    - name: Push backend image to Docker Hub (optional)
      community.docker.docker_image:
        name: "{{ backend_image }}"
        push: true
      when: backend_build_result.changed
  tags: backend

- name: Ensure Docker network exists
  community.docker.docker_network:
    name: "{{ docker_network_name }}"
    state: present

- name: Start backend container
  community.docker.docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image }}"
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
    ports:
      - "{{ backend_port }}:5000"
    env:
      NODE_ENV: "{{ node_env | default('production') }}"
  tags: backend

- name: Wait for backend to be ready
  uri:
    url: "http://{{ ansible_host | default('localhost') }}:{{ backend_port }}/api/health"
    status_code: 200
  register: backend_health
  until: backend_health.status == 200
  retries: 60
  delay: 5
  tags: backend
