---
client_image: "pereruan/img-a:v2.0.0"
client_container_name: "client-container"
client_port: 3000
client_env:
  NODE_ENV: "production"
  REACT_APP_API_URL: "http://localhost:{{ backend_port | default(5000) }}/api"